/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Neel_Esh
 */
public class AdminOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form ParticipantsOptionFrame
     */
    public AdminOptionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewAllStudentBtn = new javax.swing.JButton();
        viewAllFacuiltyBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        createMarksheetBtn = new javax.swing.JButton();
        cllgTitleLbl = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cllgDiscLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        registerStudentBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        addNewFacuiltyBtn = new javax.swing.JButton();
        removeFacuiltyBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(127, 157, 185));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewAllStudentBtn.setBackground(new java.awt.Color(173, 192, 234));
        viewAllStudentBtn.setText("View All Student");
        viewAllStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllStudentBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewAllStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 230, 40));

        viewAllFacuiltyBtn.setBackground(new java.awt.Color(173, 192, 234));
        viewAllFacuiltyBtn.setText("View All Facuilty");
        viewAllFacuiltyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllFacuiltyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewAllFacuiltyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 230, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 1040, 10));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jobParticipant.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1050, 290));

        createMarksheetBtn.setBackground(new java.awt.Color(173, 192, 234));
        createMarksheetBtn.setText("Generate Marksheet");
        createMarksheetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMarksheetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createMarksheetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 230, 40));

        cllgTitleLbl.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        cllgTitleLbl.setText("N R I GROUP OF INSTITUTE ");
        jPanel1.add(cllgTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 1050, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeproject/Logo.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cllgDiscLbl.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        cllgDiscLbl.setText("APPROVED BY AICTE, PCI, BCI & INC NEW DELHI, AFFILIATED TO RGPV, BU, BHOPAL, MPMSU || GOPAL NAGAR, BHOPAL, MADHYA PRADESH 462022");
        jPanel1.add(cllgDiscLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 910, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 900, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 1050, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1050, 10));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Manage Students -");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 1040, 10));

        registerStudentBtn.setBackground(new java.awt.Color(173, 192, 234));
        registerStudentBtn.setText("Register Student");
        registerStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStudentBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 230, 40));

        logoutBtn.setBackground(new java.awt.Color(173, 192, 234));
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, 300, 40));

        addNewFacuiltyBtn.setBackground(new java.awt.Color(173, 192, 234));
        addNewFacuiltyBtn.setText("Add New Facuilty");
        addNewFacuiltyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewFacuiltyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addNewFacuiltyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 230, 40));

        removeFacuiltyBtn.setBackground(new java.awt.Color(173, 192, 234));
        removeFacuiltyBtn.setText("Remove Facuilty");
        removeFacuiltyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFacuiltyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(removeFacuiltyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 230, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Manage Faucilty -");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 1040, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAllStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllStudentBtnActionPerformed
        // TODO add your handling code here:
        new ViewAllStudentsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewAllStudentBtnActionPerformed

    private void viewAllFacuiltyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllFacuiltyBtnActionPerformed
        // TODO add your handling code here:
        new AdminViewAllFacuiltyFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewAllFacuiltyBtnActionPerformed

    private void createMarksheetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMarksheetBtnActionPerformed
        // TODO add your handling code here:
        new ResultFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createMarksheetBtnActionPerformed

    private void registerStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStudentBtnActionPerformed
        // TODO add your handling code here:
        new StudentRegistrationFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerStudentBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void addNewFacuiltyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewFacuiltyBtnActionPerformed
        // TODO add your handling code here:
        new AdminAddNewFacuiltyFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addNewFacuiltyBtnActionPerformed

    private void removeFacuiltyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFacuiltyBtnActionPerformed
        // TODO add your handling code here:
        new AdminRemoveFacuiltyFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_removeFacuiltyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewFacuiltyBtn;
    private javax.swing.JLabel cllgDiscLbl;
    private javax.swing.JLabel cllgTitleLbl;
    private javax.swing.JButton createMarksheetBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton registerStudentBtn;
    private javax.swing.JButton removeFacuiltyBtn;
    private javax.swing.JButton viewAllFacuiltyBtn;
    private javax.swing.JButton viewAllStudentBtn;
    // End of variables declaration//GEN-END:variables
}
