/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.UsersDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import pojo.LoginPojo;


/**
 *
 * @author Neel_Esh
 */
public class AdminAddNewFacuiltyFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddNewHrFrame
     */
    public AdminAddNewFacuiltyFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtMob = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        CnfPwdTxt = new javax.swing.JPasswordField();
        PwdTxt = new javax.swing.JPasswordField();
        addNewFacuiltyBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        UpperSeperator = new javax.swing.JSeparator();
        logOutBtn = new javax.swing.JButton();
        AddNewHrLBL = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        MobLbl = new javax.swing.JLabel();
        cnfPassLbl = new javax.swing.JLabel();
        DipperSeperator = new javax.swing.JSeparator();
        nameLbl2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cllgTitleLbl = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cllgDiscLbl = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        nameLbl3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(127, 157, 185));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 210, 10));

        txtMob.setBackground(new java.awt.Color(173, 192, 234));
        txtMob.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMob.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(txtMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 310, 30));

        txtName.setBackground(new java.awt.Color(173, 192, 234));
        txtName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 310, 30));

        CnfPwdTxt.setBackground(new java.awt.Color(173, 192, 234));
        CnfPwdTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CnfPwdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(CnfPwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 600, 310, 30));

        PwdTxt.setBackground(new java.awt.Color(173, 192, 234));
        PwdTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PwdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(PwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 310, 30));

        addNewFacuiltyBtn.setBackground(new java.awt.Color(173, 192, 234));
        addNewFacuiltyBtn.setText("Add New Facuilty");
        addNewFacuiltyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewFacuiltyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addNewFacuiltyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, 400, 30));

        backBtn.setBackground(new java.awt.Color(173, 192, 234));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 110, -1));
        jPanel1.add(UpperSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1050, 10));

        logOutBtn.setBackground(new java.awt.Color(173, 192, 234));
        logOutBtn.setText("Logout");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 670, 110, -1));

        AddNewHrLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddNewHrLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNewEmp.png"))); // NOI18N
        AddNewHrLBL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(AddNewHrLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 210, 190));

        passLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        passLbl.setText("Password");
        jPanel1.add(passLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 110, 30));

        MobLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MobLbl.setText("Mobile no");
        jPanel1.add(MobLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 110, 30));

        cnfPassLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cnfPassLbl.setText("Confirm Password");
        jPanel1.add(cnfPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 150, 30));
        jPanel1.add(DipperSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 1030, 20));

        nameLbl2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nameLbl2.setText("Add New Facuilty -");
        jPanel1.add(nameLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 260, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jobParticipant.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1050, 280));

        cllgTitleLbl.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        cllgTitleLbl.setText("N R I GROUP OF INSTITUTE ");
        jPanel1.add(cllgTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 1050, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeproject/Logo.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cllgDiscLbl.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        cllgDiscLbl.setText("APPROVED BY AICTE, PCI, BCI & INC NEW DELHI, AFFILIATED TO RGPV, BU, BHOPAL, MPMSU || GOPAL NAGAR, BHOPAL, MADHYA PRADESH 462022");
        jPanel1.add(cllgDiscLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 910, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 900, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 1050, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1050, 10));

        nameLbl3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nameLbl3.setText("Name ");
        jPanel1.add(nameLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 110, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 10, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewFacuiltyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewFacuiltyBtnActionPerformed
        // TODO add your handling code here:
        if(!validateInputs())
        {   
            
            LoginPojo user=new LoginPojo();
            user.setName(txtName.getText().trim());
            user.setMobileNo(txtMob.getText().trim());
            user.setPassword(PwdTxt.getText().trim());
            user.setType("Facuilty");
            
            if(!PwdTxt.getText().trim().equalsIgnoreCase(CnfPwdTxt.getText().trim()))
            {
                JOptionPane.showMessageDialog(null,"Password & Confirm Password aren't same","Error",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            try
            {
                if(UsersDao.addNewUser(user))
                {
                    JOptionPane.showMessageDialog(null,"Facuilty Added successfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                    txtName.setText("");
                    txtMob.setText("");
                    PwdTxt.setText("");
                    CnfPwdTxt.setText("");
                    return;
                }  
                else
                {
                    JOptionPane.showMessageDialog(null,"Another Facuilty May register with the given mobile no","Sucess",JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            catch(SQLException ex)
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null,"Error while adding HR","Error",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
        }   
        else
        {   
            JOptionPane.showMessageDialog(null,"Please fill all fields","Un-Sucess",JOptionPane.INFORMATION_MESSAGE);
            return;
        }   
    }//GEN-LAST:event_addNewFacuiltyBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new AdminOptionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewFacuiltyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewFacuiltyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewFacuiltyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewFacuiltyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddNewFacuiltyFrame().setVisible(true);
            }
        });
    }
    private boolean validateInputs()
    {
        if(txtName.getText().equals("") || txtMob.getText().equals("") || PwdTxt.getText().equals("") || CnfPwdTxt.getText().equals(""))
        {
            if(pwdInputs())
            {
                return true;
            }
        }
        return false;
    }
    
    public boolean pwdInputs()
    {
        if(PwdTxt.getText().trim().equalsIgnoreCase(CnfPwdTxt.getText().trim()))
             return true;
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewHrLBL;
    private javax.swing.JPasswordField CnfPwdTxt;
    private javax.swing.JSeparator DipperSeperator;
    private javax.swing.JLabel MobLbl;
    private javax.swing.JPasswordField PwdTxt;
    private javax.swing.JSeparator UpperSeperator;
    private javax.swing.JButton addNewFacuiltyBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cllgDiscLbl;
    private javax.swing.JLabel cllgTitleLbl;
    private javax.swing.JLabel cnfPassLbl;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel nameLbl2;
    private javax.swing.JLabel nameLbl3;
    private javax.swing.JLabel passLbl;
    private javax.swing.JTextField txtMob;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}

