/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.UsersDao;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import pojo.LoginPojo;

/**
 *
 * @author Neel_Esh
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public static String userType;
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);       
    }

    private String validateUser()
    {
        if(adminJbtn.isSelected())
            return "Admin";
        else if(facBtn.isSelected())
            return "Facuilty";
        else
            return null;             
    }
    
    private boolean validateInputs() 
    {
        if(mobTxt.getText().isEmpty() || passTxt.getText().isEmpty())
            return true;
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        cllgTitleLbl1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        cllgDiscLbl1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        mobTxt = new javax.swing.JTextField();
        nameLbl2 = new javax.swing.JLabel();
        nameLbl1 = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        adminJbtn = new javax.swing.JRadioButton();
        facBtn = new javax.swing.JRadioButton();
        loginButton = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(127, 157, 185));
        jPanel3.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1050, 10));

        cllgTitleLbl1.setBackground(new java.awt.Color(127, 157, 185));
        cllgTitleLbl1.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        cllgTitleLbl1.setText("ABC GROUP OF INSTITUTE ");
        jPanel3.add(cllgTitleLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 1050, 20));

        cllgDiscLbl1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        cllgDiscLbl1.setText("APPROVED BY AICTE, PCI, BCI & INC NEW DELHI, AFFILIATED TO RGPV, BU, BHOPAL, MPMSU || GOPAL NAGAR, BHOPAL, MADHYA PRADESH 462022");
        jPanel3.add(cllgDiscLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 910, 30));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 900, 10));

        jPanel4.setBackground(new java.awt.Color(127, 157, 185));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 150));

        mobTxt.setBackground(new java.awt.Color(184, 207, 229));
        mobTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mobTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        mobTxt.setSelectionStart(1);
        jPanel3.add(mobTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 400, 30));

        nameLbl2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nameLbl2.setForeground(new java.awt.Color(0, 0, 0));
        nameLbl2.setText("Mobile No -");
        jPanel3.add(nameLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        nameLbl1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nameLbl1.setForeground(new java.awt.Color(0, 0, 0));
        nameLbl1.setText("Password -");
        jPanel3.add(nameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        passTxt.setBackground(new java.awt.Color(184, 207, 229));
        passTxt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        passTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 400, 30));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 110, 350));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 400, 10));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Select User Type :-");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        adminJbtn.setBackground(new java.awt.Color(127, 157, 185));
        buttonGroup1.add(adminJbtn);
        adminJbtn.setText("Admin");
        jPanel3.add(adminJbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 100, -1));

        facBtn.setBackground(new java.awt.Color(127, 157, 185));
        buttonGroup1.add(facBtn);
        facBtn.setText("Facuilty");
        facBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facBtnActionPerformed(evt);
            }
        });
        jPanel3.add(facBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 130, -1));

        loginButton.setBackground(new java.awt.Color(173, 192, 234));
        loginButton.setText("Login ");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel3.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 160, 30));

        exitBtn.setBackground(new java.awt.Color(173, 192, 234));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel3.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/worlp-map-in-black-h9i.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 400, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facBtnActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(validateInputs())
        {
            JOptionPane.showMessageDialog(null,"Please Fill all values","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {
            LoginPojo user=new LoginPojo();
            user.setMobileNo(mobTxt.getText().trim());
            user.setPassword(passTxt.getText());
            String type=validateUser();

            if(type!=null)
            {
                user.setType(type);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Please Select user Type","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }

            try
            {
                if(UsersDao.validateUser(user))
                {
                    if(user.getType().equals("Admin"))
                    {
                        userType="Admin";
                        JOptionPane.showMessageDialog(null,"Welcome Admin, "+user.getName(),"Success",JOptionPane.INFORMATION_MESSAGE);
                        new AdminOptionFrame().setVisible(true);
                        this.dispose();
                    }
                    else
                    {
                        userType="Facuilty";
                        JOptionPane.showMessageDialog(null,"Welcome User, "+user.getName(),"Success",JOptionPane.INFORMATION_MESSAGE);
                        new OptionFrame().setVisible(true);
                        this.dispose();
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Wrong UserId or Password or UserType","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null,"DB-error Login unsucessfull","Error",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
                return;
            }

        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminJbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cllgDiscLbl1;
    private javax.swing.JLabel cllgTitleLbl1;
    private javax.swing.JButton exitBtn;
    private javax.swing.JRadioButton facBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField mobTxt;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JLabel nameLbl2;
    private javax.swing.JPasswordField passTxt;
    // End of variables declaration//GEN-END:variables
  
}
