package gui;

import collegeproject.IdCard;
import collegeproject.ResultMaker;
import dao.StudentsDao;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import pojo.ResultPojo;
import pojo.SubjectPojo;
import pojo.StudentPojo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Neel_Esh
 */
public class ResultFrame extends javax.swing.JFrame {

    File file;
    StudentPojo student=new StudentPojo();;
    int picUpload=0;
    public ResultFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        rollNoTxt.setFocusable(true);
    }

    private void clearFields()
    {
        
        rollNoTxt.setText("");
        courseTxt.setText("");
        batchTxt.setText("");
        semTxt.setText("");
        nameTxt.setText("");
        for(int i =0;i<5;i++)
        {
            resultTbl.setValueAt("",i,0);
            resultTbl.setValueAt("",i,1);
            resultTbl.setValueAt("",i,2);
            resultTbl.setValueAt("",i,3);         
        }
       
        System.out.println(System.getProperty("user.dir"));
        file=new File(System.getProperty("user.dir")+"/src/images/uploadPicture.png");
        Image image = (new ImageIcon(file.toString())).getImage().getScaledInstance(130,160,0);
        Icon icon = new javax.swing.ImageIcon(image);
        photoLbl.setIcon(icon);
        rollNoTxt.setEditable(true);
        rollNoTxt.setFocusable(true);
        picUpload=0;
        student=null;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        cancelBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        cllgDiscLbl = new javax.swing.JLabel();
        createResult = new javax.swing.JButton();
        rollNoLbl = new javax.swing.JLabel();
        rollNoTxt = new javax.swing.JTextField();
        photoLbl = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        cllgTitleLbl = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        nameLbl = new javax.swing.JLabel();
        dateLbl1 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        courseLbl = new javax.swing.JLabel();
        courseTxt = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        batchLbl = new javax.swing.JLabel();
        batchTxt = new javax.swing.JTextField();
        dateLbl = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultTbl = new javax.swing.JTable();
        semTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(127, 157, 185));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 240, 10));

        cancelBtn.setBackground(new java.awt.Color(173, 192, 234));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, 250, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 1010, 10));

        cllgDiscLbl.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        cllgDiscLbl.setText("APPROVED BY AICTE, PCI, BCI & INC NEW DELHI, AFFILIATED TO RGPV, BU, BHOPAL, MPMSU || GOPAL NAGAR, BHOPAL, MADHYA PRADESH 462022");
        jPanel1.add(cllgDiscLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 910, 30));

        createResult.setBackground(new java.awt.Color(173, 192, 234));
        createResult.setText("Create Result");
        createResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createResultActionPerformed(evt);
            }
        });
        jPanel1.add(createResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, 420, 30));

        rollNoLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rollNoLbl.setText("Roll No -");
        jPanel1.add(rollNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        rollNoTxt.setBackground(new java.awt.Color(127, 157, 185));
        rollNoTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rollNoTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        rollNoTxt.setBorder(null);
        rollNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(rollNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 160, -1));

        photoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uploadPicture.png"))); // NOI18N
        photoLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(photoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 130, 160));

        clearBtn.setBackground(new java.awt.Color(173, 192, 234));
        clearBtn.setText("Clear Entry");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 220, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 1010, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeproject/Logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, 120, 120));

        titleLbl.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleLbl.setText("Semester Exam Result");
        jPanel1.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 910, 20));

        cllgTitleLbl.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        cllgTitleLbl.setText("N R I GROUP OF INSTITUTE ");
        jPanel1.add(cllgTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1050, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 360, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 185, 360, 10));

        nameLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameLbl.setText("Name  -");
        jPanel1.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 295, -1, -1));

        dateLbl1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dateLbl1.setText("Sem -");
        jPanel1.add(dateLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 60, -1));

        nameTxt.setEditable(false);
        nameTxt.setBackground(new java.awt.Color(127, 157, 185));
        nameTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTxt.setBorder(null);
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 295, 219, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 315, 300, 10));

        courseLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        courseLbl.setText("Course -");
        jPanel1.add(courseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        courseTxt.setEditable(false);
        courseTxt.setBackground(new java.awt.Color(127, 157, 185));
        courseTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        courseTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        courseTxt.setBorder(null);
        jPanel1.add(courseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 329, 300, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 1000, 10));

        batchLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        batchLbl.setText("Batch -");
        jPanel1.add(batchLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        batchTxt.setEditable(false);
        batchTxt.setBackground(new java.awt.Color(127, 157, 185));
        batchTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        batchTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        batchTxt.setBorder(null);
        jPanel1.add(batchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 110, -1));

        dateLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dateLbl.setText("Date -");
        jPanel1.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 60, -1));

        dateTxt.setEditable(false);
        dateTxt.setBackground(new java.awt.Color(127, 157, 185));
        dateTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dateTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dateTxt.setBorder(null);
        jPanel1.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 120, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        resultTbl.setBackground(new java.awt.Color(173, 192, 234));
        resultTbl.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        resultTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Subject", "Grade", "Sub - Credit", "Marks Obtained"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        resultTbl.setAutoscrolls(false);
        resultTbl.setMaximumSize(new java.awt.Dimension(300, 195));
        resultTbl.setMinimumSize(new java.awt.Dimension(300, 195));
        resultTbl.setPreferredSize(new java.awt.Dimension(300, 200));
        resultTbl.setRowHeight(40);
        resultTbl.setRowSelectionAllowed(false);
        resultTbl.setShowGrid(true);
        resultTbl.setSize(new java.awt.Dimension(300, 190));
        resultTbl.getTableHeader().setResizingAllowed(false);
        resultTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(resultTbl);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 1010, 220));

        semTxt.setBackground(new java.awt.Color(127, 157, 185));
        semTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        semTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        semTxt.setBorder(null);
        jPanel1.add(semTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createResultActionPerformed
    //if(validateInput())
    {
        
        if(student==null)
            student=new StudentPojo();
        
        ResultPojo result=new ResultPojo();
        for(int i =0;i<5;i++)
        {
            SubjectPojo sub=new SubjectPojo();  
            sub.setSubject((String)resultTbl.getValueAt(i,0));
            sub.setGrade((String)resultTbl.getValueAt(i,1));
            sub.setSubCredit((int)resultTbl.getValueAt(i,2));
            sub.setMarksObt((int)resultTbl.getValueAt(i,3));
            result.addSubjectInList(sub);
        }
        
        try
        {   
            if(ResultMaker.createMarkSheet(result, student))
            {
               JOptionPane.showMessageDialog(null,"MarkSheet Created Successfully","Success Messege",JOptionPane.INFORMATION_MESSAGE);
               clearFields();
               return; 
            }
            else
            {
               JOptionPane.showMessageDialog(null,"SomeThing went wrong","Error Messege",JOptionPane.ERROR_MESSAGE);
               return; 
            }    
        }
        catch(IOException ex)
        {
            System.out.println("Error in");
            JOptionPane.showMessageDialog(null,"Error While Creating a markSheet","Error Messege",JOptionPane.ERROR_MESSAGE);
            return; 
        }
    }
//    else
//    {
//        JOptionPane.showMessageDialog(null,"Please Fill all the fields","Error Messege",JOptionPane.ERROR_MESSAGE);
//        return;
//    } 
    }//GEN-LAST:event_createResultActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
            if(LoginFrame.userType=="Admin")
        {
            new AdminOptionFrame().setVisible(true);
            this.dispose();
        }
        else
        {
            new OptionFrame().setVisible(true);
            this.dispose();
        } 
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void rollNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNoTxtActionPerformed
        // TODO add your handling code here:
        try
        {
            student=StudentsDao.getStudentByRollNo(rollNoTxt.getText().trim());
            if(student!=null)
            {
                nameTxt.setText(student.getName());
                courseTxt.setText(student.getCourse()+"( "+student.getBranch()+" )");
                batchTxt.setText(student.getBatch());
                semTxt.setText(student.getSem());
                
                file=new File(System.getProperty("user.dir")+"/src/temp/"+rollNoTxt.getText().trim()+".png");
                Image image = (new ImageIcon(file.toString())).getImage().getScaledInstance(130,160,0);
                Icon icon = new javax.swing.ImageIcon(image);
                photoLbl.setIcon(icon);
                
                SimpleDateFormat formatter = new SimpleDateFormat("dd-MMM-yyyy");  
                Date date = new Date(); 
                dateTxt.setText(formatter.format(date));
                rollNoTxt.setEditable(false);
                return;
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"Error While retriving Record","Error Messege",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return; 
        }
        catch(FileNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,"Error While retriving image","Error Messege",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return; 
        }
        catch(IOException ex)
        {
            JOptionPane.showMessageDialog(null,"Error While retriving image","Error Messege",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return; 
        }
        
    }//GEN-LAST:event_rollNoTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultFrame().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batchLbl;
    private javax.swing.JTextField batchTxt;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel cllgDiscLbl;
    private javax.swing.JLabel cllgTitleLbl;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JTextField courseTxt;
    private javax.swing.JButton createResult;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel dateLbl1;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JTable resultTbl;
    private javax.swing.JLabel rollNoLbl;
    private javax.swing.JTextField rollNoTxt;
    private javax.swing.JTextField semTxt;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
        if(rollNoTxt.getText().isEmpty()|| courseTxt.getText().isEmpty())
            return false; 
        return true;
    }
}
