package gui;

//import dao.HrDao;
//import dao.ParticipantsDao;
//import dao.UserDao;
//import pojo.CurrentUser;
//import pojo.LoginPojo;
//import pojo.StudentPojo;

import collegeproject.IdCard;
import dao.CitiesDao;
import dao.StudentsDao;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import pojo.StudentPojo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Neel_Esh
 */
public class StudentRegistrationFrame extends javax.swing.JFrame {

    File file;
    StudentPojo students=new StudentPojo();;
    int picUpload=0;
    public StudentRegistrationFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void clearFields()
    {
        rollNoTxt.setText("");
        nameTxt.setText("");
        emailTxt.setText("");
        phoneTxt.setText("");
        courseTxt.setText("");
        branchTxt.setText("");
        addressTxt1.setText("");
        addressTxt2.setText("");
        semTxt.setText("");
        sessionTxt.setText("");
        stateJcb.setSelectedIndex(0);
        bg1.clearSelection();
        
        file=new File(System.getProperty("user.dir")+"/src/images/uploadPicture.png");
        Image image = (new ImageIcon(file.toString())).getImage().getScaledInstance(130,160,0);
        Icon icon = new javax.swing.ImageIcon(image);
        photoLbl.setIcon(icon);
        
        //photoLbl.setText("Upload Picture");
        picUpload=0;
        students=null;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        bckBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        genderLbl = new javax.swing.JLabel();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        registerUser = new javax.swing.JButton();
        mailLbl = new javax.swing.JLabel();
        address2Lbl = new javax.swing.JLabel();
        addressTxt2 = new javax.swing.JTextField();
        nameLbl1 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        photoBtn = new javax.swing.JButton();
        mailLbl1 = new javax.swing.JLabel();
        rollNoTxt = new javax.swing.JTextField();
        courseLbl = new javax.swing.JLabel();
        courseTxt = new javax.swing.JTextField();
        rollNoLbl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        photoLbl = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        sessionTxt = new javax.swing.JTextField();
        sessionLbl = new javax.swing.JLabel();
        address1Lbl = new javax.swing.JLabel();
        addressTxt1 = new javax.swing.JTextField();
        stateLbl = new javax.swing.JLabel();
        CityLbl = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        cityJcb = new javax.swing.JComboBox<>();
        cllgTitleLbl = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cllgDiscLbl = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        semTxt = new javax.swing.JTextField();
        semLbl = new javax.swing.JLabel();
        stateJcb = new javax.swing.JComboBox<>();
        branchTxt = new javax.swing.JTextField();
        branchLbl = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(127, 157, 185));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 394, 240, 20));

        bckBtn.setBackground(new java.awt.Color(173, 192, 234));
        bckBtn.setText("Back");
        bckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bckBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 660, 190, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 1010, 10));

        genderLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        genderLbl.setText("Gender -");
        jPanel1.add(genderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        maleBtn.setBackground(new java.awt.Color(127, 157, 185));
        bg1.add(maleBtn);
        maleBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        maleBtn.setText("Male");
        jPanel1.add(maleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 100, -1));

        femaleBtn.setBackground(new java.awt.Color(127, 157, 185));
        bg1.add(femaleBtn);
        femaleBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        femaleBtn.setText("Female");
        jPanel1.add(femaleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 130, -1));

        registerUser.setBackground(new java.awt.Color(173, 192, 234));
        registerUser.setText("Register Student");
        registerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserActionPerformed(evt);
            }
        });
        jPanel1.add(registerUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, 550, 30));

        mailLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        mailLbl.setText("Email -");
        jPanel1.add(mailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        address2Lbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        address2Lbl.setText("Address 2 -");
        jPanel1.add(address2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        addressTxt2.setBackground(new java.awt.Color(173, 192, 234));
        addressTxt2.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        addressTxt2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addressTxt2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        addressTxt2.setSelectionStart(1);
        jPanel1.add(addressTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 240, 30));

        nameLbl1.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        nameLbl1.setText("Name -");
        jPanel1.add(nameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        nameTxt.setBackground(new java.awt.Color(173, 192, 234));
        nameTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        nameTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        nameTxt.setSelectionStart(1);
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 400, 30));

        emailTxt.setBackground(new java.awt.Color(173, 192, 234));
        emailTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        emailTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        emailTxt.setSelectionStart(1);
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 400, 30));

        phoneTxt.setBackground(new java.awt.Color(173, 192, 234));
        phoneTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        phoneTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        phoneTxt.setSelectionStart(1);
        jPanel1.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 400, 30));

        photoBtn.setBackground(new java.awt.Color(173, 192, 234));
        photoBtn.setText("Upload Photo");
        photoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(photoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 180, 30));

        mailLbl1.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        mailLbl1.setText("Phone -");
        jPanel1.add(mailLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        rollNoTxt.setBackground(new java.awt.Color(173, 192, 234));
        rollNoTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        rollNoTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        rollNoTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        rollNoTxt.setSelectionStart(1);
        jPanel1.add(rollNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 400, 30));

        courseLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        courseLbl.setText("Course -");
        jPanel1.add(courseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        courseTxt.setBackground(new java.awt.Color(173, 192, 234));
        courseTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        courseTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        courseTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        courseTxt.setSelectionStart(1);
        jPanel1.add(courseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 400, 30));

        rollNoLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        rollNoLbl.setText("Roll No -");
        jPanel1.add(rollNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 530, 30));

        photoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uploadPicture.png"))); // NOI18N
        photoLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(photoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 130, 160));

        clearBtn.setBackground(new java.awt.Color(173, 192, 234));
        clearBtn.setText("Clear Entry");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 190, 30));

        sessionTxt.setBackground(new java.awt.Color(173, 192, 234));
        sessionTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        sessionTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sessionTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        sessionTxt.setSelectionStart(1);
        jPanel1.add(sessionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 240, 30));

        sessionLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        sessionLbl.setText("Session -");
        jPanel1.add(sessionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 140, -1));

        address1Lbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        address1Lbl.setText("Address 1 -");
        jPanel1.add(address1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        addressTxt1.setBackground(new java.awt.Color(173, 192, 234));
        addressTxt1.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        addressTxt1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addressTxt1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        addressTxt1.setSelectionStart(1);
        jPanel1.add(addressTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 240, 30));

        stateLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        stateLbl.setText("State -");
        jPanel1.add(stateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        CityLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        CityLbl.setText("City -");
        jPanel1.add(CityLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 60, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 530, 20));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 10, 380));

        cityJcb.setBackground(new java.awt.Color(173, 192, 234));
        cityJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select State First" }));
        cityJcb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cityJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 240, 30));

        cllgTitleLbl.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        cllgTitleLbl.setText("N R I GROUP OF INSTITUTE ");
        jPanel1.add(cllgTitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 1050, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeproject/Logo.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cllgDiscLbl.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        cllgDiscLbl.setText("APPROVED BY AICTE, PCI, BCI & INC NEW DELHI, AFFILIATED TO RGPV, BU, BHOPAL, MPMSU || GOPAL NAGAR, BHOPAL, MADHYA PRADESH 462022");
        jPanel1.add(cllgDiscLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 910, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 900, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 1050, 20));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1050, 10));

        semTxt.setBackground(new java.awt.Color(173, 192, 234));
        semTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        semTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        semTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        semTxt.setSelectionStart(1);
        jPanel1.add(semTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 240, 30));

        semLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        semLbl.setText("Semester -");
        jPanel1.add(semLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, -1, -1));

        stateJcb.setBackground(new java.awt.Color(173, 192, 234));
        stateJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Dadra and Nagar Haveli", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Karnatka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Puducherry", "Punjab", "Rajasthan", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal" }));
        stateJcb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stateJcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJcbActionPerformed(evt);
            }
        });
        jPanel1.add(stateJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 240, 30));

        branchTxt.setBackground(new java.awt.Color(173, 192, 234));
        branchTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        branchTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        branchTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        branchTxt.setSelectionStart(1);
        jPanel1.add(branchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 400, 30));

        branchLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        branchLbl.setText("Branch -");
        jPanel1.add(branchLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 240, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserActionPerformed
    if(validateInput())
    {
        String gen=getGender();
        if(gen==null || picUpload==0)
        { 
            JOptionPane.showMessageDialog(null,"Please select Gender or upload photo","Error Messege",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(students==null)
            students=new StudentPojo();
        students.setRollNo(rollNoTxt.getText().trim());
        students.setName(nameTxt.getText().trim());
        students.setEmail(emailTxt.getText().trim().toUpperCase());
        students.setPhone(phoneTxt.getText().trim());
        students.setAddress(addressTxt1.getText().trim()+" , "+addressTxt2.getText().trim()+" , "+(String)cityJcb.getSelectedItem()+" , "+(String)stateJcb.getSelectedItem());
        students.setCourse(courseTxt.getText().trim());
        students.setBranch(branchTxt.getText().trim());
        students.setSem(semTxt.getText().trim());
        students.setBatch(sessionTxt.getText().trim());
        students.setGender(gen);
        
        if(!emailTxt.getText().contains("@") || !emailTxt.getText().contains(".com"))
        {
            JOptionPane.showMessageDialog(null,"Please enter valid mail","Error Messege",JOptionPane.ERROR_MESSAGE);
            return;
        }
  
        try
        {   
            IdCard.createIdCard(students,file.toString());
            if(StudentsDao.addNewStudents(students))
            {
               JOptionPane.showMessageDialog(null,"Entey Submitted Successfully in DB","Success Messege",JOptionPane.INFORMATION_MESSAGE);
               clearFields();
               return; 
            }
            else
            {
               JOptionPane.showMessageDialog(null,"Duplicate Entry Found or May connection issue","Error Messege",JOptionPane.ERROR_MESSAGE);
               return; 
            }    
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
            System.out.println("Error in DBConnection :- "+ex.getMessage());
        } 
        catch(IOException ex)
        {
            System.out.println("Error in");
            JOptionPane.showMessageDialog(null,"Error While Creating an IdCard","Error Messege",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return; 
        }
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Please Fill all the fields","Error Messege",JOptionPane.ERROR_MESSAGE);
        return;
    } 
    }//GEN-LAST:event_registerUserActionPerformed

    private void bckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckBtnActionPerformed
        if(LoginFrame.userType=="Admin")
        {
            new AdminOptionFrame().setVisible(true);
            this.dispose();
        }
        else
        {
            new OptionFrame().setVisible(true);
            this.dispose();
        }      
    }//GEN-LAST:event_bckBtnActionPerformed

    private void photoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoBtnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.setDialogTitle("Browse Files");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int result =chooser.showOpenDialog(null);
        
        if (result == chooser.APPROVE_OPTION) 
        {   
            try
            {
                file=chooser.getSelectedFile();
                Image image = (new ImageIcon(file.toString())).getImage().getScaledInstance(130,160, 0);
                Icon icon = new javax.swing.ImageIcon(image);
                photoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                photoLbl.setIcon(icon);
                if(students==null)
                    students=new StudentPojo();
                students.setFile(new FileInputStream(file.toString()));
                picUpload=1;
            }
            catch(FileNotFoundException ex)    
            {
                System.out.println("File Not FOund Exception\nWhile Upload Image");
            }
        } 
        else if (result == chooser.CANCEL_OPTION) 
        {
            System.out.println("Cancel was selected");
        }
    }//GEN-LAST:event_photoBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void stateJcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJcbActionPerformed
        // TODO add your handling code here:
        cityJcb.removeAllItems();
        //cityJcb.addItem("Please Select State First");
        try
        {
            if(stateJcb.getSelectedIndex()==-1 || stateJcb.getSelectedIndex()==0)
            {
                JOptionPane.showMessageDialog(null,"Please select Any State","Warning",JOptionPane.WARNING_MESSAGE);
                return; 
            }
            List<String> cities=CitiesDao.getAllCitiesByState((String)stateJcb.getSelectedItem());
            int i=0;
            for(String city:cities)
            {
                cityJcb.addItem(city);
            }
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
            System.out.println("Error in DBConnection :- "+ex.getMessage());
        } 
    }//GEN-LAST:event_stateJcbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistrationFrame().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityLbl;
    private javax.swing.JLabel address1Lbl;
    private javax.swing.JLabel address2Lbl;
    private javax.swing.JTextField addressTxt1;
    private javax.swing.JTextField addressTxt2;
    private javax.swing.JButton bckBtn;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JLabel branchLbl;
    private javax.swing.JTextField branchTxt;
    private javax.swing.JComboBox<String> cityJcb;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel cllgDiscLbl;
    private javax.swing.JLabel cllgTitleLbl;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JTextField courseTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel mailLbl;
    private javax.swing.JLabel mailLbl1;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton photoBtn;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JButton registerUser;
    private javax.swing.JLabel rollNoLbl;
    private javax.swing.JTextField rollNoTxt;
    private javax.swing.JLabel semLbl;
    private javax.swing.JTextField semTxt;
    private javax.swing.JLabel sessionLbl;
    private javax.swing.JTextField sessionTxt;
    private javax.swing.JComboBox<String> stateJcb;
    private javax.swing.JLabel stateLbl;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
        if(nameTxt.getText().isEmpty() || emailTxt.getText().isEmpty() ||
                addressTxt2.getText().isEmpty() || courseTxt.getText().isEmpty() || 
                rollNoTxt.getText().isEmpty()|| phoneTxt.getText().isEmpty())
            return false; 
        return true;
    }
    
//    private boolean

    private String getGender() {
        if(maleBtn.isSelected())
            return "Male";
        if(femaleBtn.isSelected())
            return "Female";
        return null;
    }
}
